CREATE TABLE IF NOT EXISTS RADA (
  ID SERIAL,
  X DECIMAL(12,10) NOT NULL,
  Y DECIMAL(12,10) NOT NULL,
  Nimi VARCHAR(300) NOT NULL,
  Kirjeldus VARCHAR(300) NULL,
  PRIMARY KEY (ID));
  
CREATE TABLE IF NOT EXISTS PUNKT (
  ID SERIAL,
  X DECIMAL(12,10) NOT NULL,
  Y DECIMAL(12,10) NOT NULL,
  kysimus VARCHAR(300) NOT NULL,
  vastus1 VARCHAR(300) NOT NULL,
  vastus2 VARCHAR(300) NOT NULL,
  vastus3 VARCHAR(300) NOT NULL,
  vastus4 VARCHAR(300) NOT NULL,
  Nimi VARCHAR(45) NOT NULL,
  Rada INT NOT NULL,  
  PRIMARY KEY (ID));
  
CREATE TABLE IF NOT EXISTS KASUTAJA (
  ID SERIAL,
  Administraator BOOLEAN DEFAULT NULL,
  Eesinimi VARCHAR(45) NOT NULL,
  Perekonnanimi VARCHAR(45) NOT NULL,
  Parool VARCHAR(45) NOT NULL,
  Kasutajanimi VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID));
  
 CREATE TABLE IF NOT EXISTS TULEMUS (
  ID SERIAL,
  KasutajaID INT NOT NULL,
  RadaID INT NOT NULL,
  Punktid INT NOT NULL,
  Aeg INT NOT NULL,
  PRIMARY KEY (ID));
  
  INSERT INTO KASUTAJA (Administraator, Eesinimi, Perekonnanimi, Parool, Kasutajanimi) VALUES (TRUE, 'Siim', 'Neljandik', 'Password1', 'Mina');
  INSERT INTO RADA (ID,  X, Y, Nimi, Kirjeldus) VALUES (1, 12.1231231233, 12.1231231233, 'Tartu', 'Lahe rada');
