default: &default
  pool: 5
  adapter: postgresql
  encoding: unicode
  host: ec2-54-83-17-9.compute-1.amazonaws.com
  database: d1mc8epbsl42nv
  username: mdcyboqdwligkh
  password: "mJyjNwxYcFj-5gqLjPFIJJLq7z"

development:
  pool: 5
  adapter: postgresql
  encoding: unicode
  host: ec2-54-83-17-9.compute-1.amazonaws.com
  database: d1mc8epbsl42nv
  username: mdcyboqdwligkh
  password: "mJyjNwxYcFj-5gqLjPFIJJLq7z"

test:
  <<: *default
  database: orienteerumine_test

production:
  <<: *default