# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a528efd99c8306f52f80da1d30d6d77c281f1c17bc459e243bb87c572639fc8ca66b7ef76303a394582ecf543dd91963a4a2fc5bfbb0a87540b3ad29080ec037

test:
  secret_key_base: 88c5a811a8178a717907a04289ae28a8e77e4ad9a02fda470262357062e9dcc3daa891e4abfef74b7c6d9d48197bd1c581945c6c7d46850846528a0905a8cb4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
